- name: Install docker stuff
  hosts: "{{ host }}"
  tasks:

  - name: apt update 2
    become: yes
    apt:
      update_cache: yes

  - name: install prerequisites for Docker repository
    become: yes
    ansible.builtin.apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg2
        - lsb-release

  - name: add docker apt key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  - name: install docker and its dependencies
    become: yes
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - python3-docker
        - docker-compose
      state: present

  - name: start and enable docker daemon
    become: yes
    service:
      name: docker
      state: started
      enabled: yes

  - name: start and enable containerd daemon
    become: yes
    service:
      name: containerd
      state: started
      enabled: yes

  - name: Add Anisble user to the docker group
    become: yes
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

